# Generated by Django 4.0.6 on 2022-07-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='max_student',
            field=models.PositiveIntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_app.school'),
        ),
        migrations.AddField(
            model_name='course',
            name='type_of_education',
            field=models.TextField(blank=True, null=True),
        ),
    ]
