# Generated by Django 4.0.6 on 2022-07-11 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_max_student_course_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='max_student',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
